### PR TITLE
Refactor get_cluster to call list_clusters

### PR DESCRIPTION
**Pull request by kshileeva**
Addresses #512

### CODE REVIEW

**Comment by Westwooo** [comment]
@kshileeva Thank you for the contribution, all looks good to me. Before it can be merged please can you sign the contributor agreement. It can be done electronically through here: : https://review.couchbase.org/settings/#Agreements.

**Comment by kshileeva** [comment]
@Westwooo Thank you, the agreement is signed. For the future, should I ask to be assigned to an issue in a conversation?

**Comment by Westwooo** [comment]
> @Westwooo Thank you, the agreement is signed. For the future, should I ask to be assigned to an issue in a conversation?

There's no need to, feel free to pick up any issues that seem interesting, but those labeled "good first issues" are a good place to start. But if you have any questions/suggestions feel free to reach out any time.

**Comment by Westwooo** [comment]
@kshileeva I can't see a record of the agreement being signed, did you use the same e-mail as that associated with your github account? If not which e-mail did you use?

**Comment by Westwooo** [comment]
> > @kshileeva I can't see a record of the agreement being signed, did you use the same e-mail as that associated with your github account? If not which e-mail did you use?
> 
> I added the same email I use for github after signing the agreement

Is that the gmail address?

**Comment by kshileeva** [comment]
> > > @kshileeva I can't see a record of the agreement being signed, did you use the same e-mail as that associated with your github account? If not which e-mail did you use?
> > 
> > 
> > I added the same email I use for github after signing the agreement
> 
> Is that the gmail address?

Yes

**Comment by Westwooo** [comment]
> > > > @kshileeva I can't see a record of the agreement being signed, did you use the same e-mail as that associated with your github account? If not which e-mail did you use?
> > > 
> > > 
> > > I added the same email I use for github after signing the agreement
> > 
> > 
> > Is that the gmail address?
> 
> Yes

Please could you re-sign it and I'll check if it comes through this time, it might not have worked if your email was not associated with your gerrit account before signing

**Comment by kshileeva** [comment]
> > > > > @kshileeva I can't see a record of the agreement being signed, did you use the same e-mail as that associated with your github account? If not which e-mail did you use?
> > > > 
> > > > 
> > > > I added the same email I use for github after signing the agreement
> > > 
> > > 
> > > Is that the gmail address?
> > 
> > 
> > Yes
> 
> Please could you re-sign it and I'll check if it comes through this time, it might not have worked if your email was not associated with your gerrit account before signing

Couldn't find an option to re-sign in settings, so sent a copy to the couchbase info email

**Pull request merged**
